server:
  port: 8080

dataSource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/project_1

jwt:
  secret-key-source: ${JWT_SECRET_KEY}

logging:
  config: classpath:logback-spring-local.xml
  level:
    org:
      hibernate:
        SQL: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false